baseURL = "https://ghostmaker92.github.io/hugo"
languageCode = "en-us"
title = "El sitio de Hugo de Daniel Radomirov"
theme = ['relearn']
[params]    
themeVariant = "blue"


[[menu.shortcuts]]
name = "<i class='fas fa-code-branch'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/ghostmaker92"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-youtube'></i> Canal Youtube"
identifier ="youtube"
url = "https://www.youtube.com/channel/UCv85NiROLKddHa0fBATwTzw"
weight = 11

[[menu.shortcuts]]
name = "<i class='far fa-file'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 12

[[menu.shortcuts]]
name = "<i class='fab fa-stack-overflow'></i> Stack Overflow"
url = "https://es.stackoverflow.com"
weight = 13